// hamburn-cozynights/src/lib/components/LegalLinks.svelte
<!--
@component
Links to the legal notice (Impressum), the privacy policy
(Datenschutzerklärung) and the booking rules (Buchungsregeln). German law wants
the first two clearly labelled and reachable
from every page; the root layout shows them in the footer, full-screen pages
place them themselves.
-->
<nav class="legal-links" aria-label="Legal">
	<a href="/impressum" lang="de">Impressum</a>
	<span aria-hidden="true">·</span>
	<a href="/datenschutz" lang="de">Datenschutz</a>
	<span aria-hidden="true">·</span>
	<a href="/buchungsregeln" lang="de">Buchungsregeln</a>
</nav>

<style>
	.legal-links {
		display: inline-flex;
		align-items: center;
		gap: 0.4rem;
		font-family: 'Inter', system-ui, sans-serif;
		font-size: 0.78rem;
		font-weight: 600;
		letter-spacing: 0.02em;
	}

	a {
		display: inline-flex;
		align-items: center;
		min-height: 28px;
		padding: 0 0.2rem;
		border-radius: 6px;
		color: #a3a3a3;
		text-decoration: none;
	}

	a:hover {
		color: #fff;
		text-decoration: underline;
		text-underline-offset: 3px;
	}

	a:focus-visible {
		outline: 2px solid #fff;
		outline-offset: 2px;
	}

	span {
		color: #525252;
	}
</style>

// docs/.vitepress/theme/LegalLinks.vue
<!--
Links to the app's legal notice, privacy policy and booking rules under every
doc page.
VitePress only shows its footer on pages without a sidebar, so doc pages get
this instead (see index.ts). The addresses come from `themeConfig.legal` in
config.mts. target="_self" keeps the VitePress router from treating them as
doc pages: they belong to the app.
-->
<script setup lang="ts">
import { useData } from 'vitepress';
import type { CozyThemeConfig } from '../config.mts';

const { theme } = useData<CozyThemeConfig>();
</script>

<template>
	<nav v-if="theme.legal" class="legal-links" aria-label="Legal">
		<a :href="theme.legal.impressum" target="_self" lang="de">Impressum</a>
		<span aria-hidden="true">·</span>
		<a :href="theme.legal.privacy" target="_self" lang="de">Datenschutz</a>
		<span aria-hidden="true">·</span>
		<a :href="theme.legal.rules" target="_self" lang="de">Buchungsregeln</a>
	</nav>
</template>

<style scoped>
.legal-links {
	display: flex;
	justify-content: center;
	gap: 0.5rem;
	margin-top: 3rem;
	padding-top: 1rem;
	border-top: 1px solid var(--vp-c-divider);
	color: var(--vp-c-text-3);
	font-size: 0.8rem;
}

.legal-links a {
	color: var(--vp-c-text-2);
	text-decoration: none;
}

.legal-links a:hover {
	color: var(--vp-c-brand-1);
	text-decoration: underline;
}
</style>
